#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  block compile bundler
  mkdir -p "$shome/bin"
  ln -nfs ../vendor/bundle/bin/t "$shome/bin/"
}

bootstrap
